import * as React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Container } from "./components/container";
import Navigation from "./components/navigation";
import Footer from "./components/footer";
import { ThemeProvider } from "./components/theme-provider";
import { useScroll } from "react-use";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            {/* <body className={inter.className}> */}
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className=" bg-background_second">
                        <Container
                            className="bg-background min-h-screen shadow-sm shadow-zinc-200 dark:shadow-zinc-500"
                            variant={"fullMobileConstrainedPadded"}
                        >
                            <Navigation />
                            <div className="pt-40">{children}</div>
                            <Footer />
                        </Container>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
