import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Container } from "./components/container";
import Navigation from "./components/navigation";
import Footer from "./components/footer";
import { ThemeProvider } from "./components/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            {/* <body className={inter.className}> */}
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className=" bg-[#FAFAFA]">
                        <Container
                            className="bg-white min-h-screen shadow-sm"
                            variant={"fullMobileConstrainedPadded"}
                        >
                            <div className="px-0 sm:px-10 md:px-20">
                                <Navigation />
                                <div className="mt-20">{children}</div>
                                <Footer />
                            </div>
                        </Container>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
