import { IProject } from "../types/project";

export const listOfProjects: IProject[] = [
    {
        title: "Project 1",
        description:
            "Planetaria Creating technology to empower civilians to explore space on their own terms",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 2",
        description: "Description of the project 2",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 3",
        description: "Description of the project 3",
        githubLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 4",
        description: "Description of the project 4",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 5",
        description: "Description of the project 5",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 6",
        description: "Description of the project 6",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 7",
        description: "Description of the project 7",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 8",
        description: "Description of the project 8",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 9",
        description: "Description of the project 9",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 10",
        description: "Description of the project 10",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 11",
        description: "Description of the project 11",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 12",
        description: "Description of the project 12",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 13",
        description: "Description of the project 13",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
    {
        title: "Project 14",
        description: "Description of the project 14",
        githubLink: "#",
        previewLink: "#",
        logo: "/images/sample-icons.svg",
        coverImage: "/images/project-1.webp",
    },
];

export const rotates = [
    "rotate-2",
    "rotate-3",
    "rotate-4",
    "rotate-6",

    "-rotate-2",
    "-rotate-3",
    "-rotate-4",
    "-rotate-6",
];
