import { HomeContent } from "@/components";
import { useStoreShowNavbar } from "@/store";
import styles from "@/styles/Home.module.css";
import { Container, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  const { setIsTransitionTrue } = useStoreShowNavbar((state) => state);
  useEffect(() => {
    setIsTransitionTrue();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="container.sm" paddingTop={"12rem"}>
          <HomeContent />
        </Container>
      </main>
    </>
  );
}
